version: "3.3"

services:

  deon:
    image: deon/core-service:latest
    container_name: deon.example.com
    build: .
    ports:
      - "8001:8001"
    networks:
      - net_byfn
    volumes:
      - type: bind
        source: ~/deon/fabric-samples/first-network/channel-artifacts
        target: /config/channel-artifacts
        read_only: true
      - type: bind
        source: ~/deon/fabric-samples/first-network/crypto-config
        target: /config/crypto-config
        read_only: true
      - type: volume
        source: state-store
        target: /tmp/state-store
    depends_on:
      - ipfs

  ipfs:
    image: ipfs/go-ipfs:latest
    container_name: ipfs.node.example.com
    ports:
      - "8080:8080"
      - "4001:4001"
      - "5001:5001"
    volumes:
      - "/tmp/ipfs-docker-staging:/export"
      - "/tmp/ipfs-docker-data:/data/ipfs"
    networks:
      - net_byfn

networks:
  net_byfn:
    external: true

volumes:
  state-store: